### ISSUE TITLE
New feature: A max_age param for try_lock()

### ISSUE THREAD

**Issue by kablamo** [trinitum/perl-File-Flock-Tiny#3]
```
trylock($file, $max_age);
```

If the file is locked and the file timestamp > $max_age, then:
1. kill $pid
2. rm the file
3. acquire a new lock.

**Comment by trinitum** [comment]
Thanks for the suggestion but no. This logic in my opinion is outside of the Tiny module scope. Besides, I don't see how this behavior can be justified. Note, that this module is called "File::Flock::Tiny", and not "File::Pid::Tiny" (although indeed it can be used to create pid files), and the purpose of `trylock` is to lock a file of unspecified type, not just a pid file, so assumption that this file has to contain pid is wrong. And if this is not a pid file, then removing it also may be not a good idea, and even if it is a pid file you might want instead of removing it wait till lock will be released, because process may be slow to exit, or if you SIGKILL it it may leave some children still holding the lock.
